### ISSUE TITLE
Used access token in plugin no metaData> githubData response or error

### ISSUE THREAD

**Issue by jurra** [lindsaykwardell/gridsome-source-github-api#1]
Hi @lindsaykwardell. I have been trying to use your plugin. 
- I used the following configuration of your project, and the githubData for some reason doesn't load.
- I tested the query in github explorer and works fine.
- I also don't get any error, so I have no idea what is going on

This is the current plugin configuration I am using, thank you
```
use: `gridsome-source-github-api`,
      options: {
        // token: required by the GitHub API
        token: myToken,
  
        // GraphQLquery: defaults to a search query
        graphQLQuery: `{
          organization(login:"open-hardware-leaders"){
             repositories(first:10){
              edges{
                node{
                  name
                }
              }
            }
          }
        }`,
```

**Comment by jurra** [comment]
I am working on a project related to covid19 where I want to use your plugin, maybe the project is also interesting to you: https://github.com/CombatCovid/SPA-website

**Comment by lindsaykwardell** [comment]
Hi @jurra!

I believe the issue in this case is that the GraphQL query needs to be wrapped in `query { }`. I was able to run your snippet on my computer like this:

```
{
      use: "gridsome-source-github-api",
      options: {
        token: process.env.GITHUB_API_TOKEN,
        variables: {},
        graphQLQuery: `
            query {
              organization(login:"open-hardware-leaders"){
                repositories(first:10){
                  edges{
                    node{
                      name
                    }
                  }
                }
              }
            }
          `,
      },
    },
```
I'm not certain where the error is getting swallowed, but I've added a new error if the query block is missing from the GraphQL query. I'll be running a new pull request shortly.

Let me know if that works for you. Thanks for the feedback!

**Comment by jurra** [comment]
Great I will try that!! Thank you very much!!

**Comment by jurra** [comment]
Now I am getting an error, thats good : Missing API token!
If I just copy and paste the token is not working for some reason, but thats something I should figure out. Thank you once again!

**Comment by lindsaykwardell** [comment]
> Now I am getting an error, thats good : Missing API token!
> If I just copy and paste the token is not working for some reason, but thats something I should figure out. Thank you once again!

Glad to help! I used the environment variable from my code, might not match yours.

I'll merge in the pull request with the new error and release a new version shortly.
