### ISSUE TITLE
Graphql-fetch dependencies

### ISSUE THREAD

**Issue by tolerl1** [lindsaykwardell/gridsome-source-github-api#8]
Graphql-fetch appears to be unmaintained as there is a vulnerability for node-fetch: https://npmjs.com/advisories/1556

gridsome-source-github-api -> Graphql-fetch -> isomorphic-fetch -> node-fetch

isomorphic-fetch v3 resolves this but Graphql-fetch has not updated its version of isomorphic-fetch.

I used npm shrinkwrap to fix it myself but it would be nice to have it fixed at the higher-level.

Is there a similar package to Graphql-fetch that provides the same functionality? Or possible for you to incorporate an updated version of it into this package?

<img width="572" alt="Screen Shot 2020-11-09 at 16 17 34" src="https://user-images.githubusercontent.com/7991194/98597477-19a41a80-22a7-11eb-8cf6-e52e3504ef5c.png">

**Comment by lindsaykwardell** [comment]
Hi! Thanks for letting me know about this.

I've updated to just use isomorphic-fetch directly. Removed graphql-fetch altogether.

Let me know if you have any more issues.

**Comment by lindsaykwardell** [comment]
Latest NPM build is 0.2.0 with this change.
